apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wiz-sa
  namespace: wiz
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: wiz-sa

  data:
    - secretKey: clientId
      remoteRef:
        key: jlarrea-k8s-secret
        property: clientId
    - secretKey: clientToken
      remoteRef:
        key: jlarrea-k8s-secret
        property: clientToken